# Expose port 80
FROM nginx:alpine

# Expose port 80
LABEL maintainer 'Renato Matos'

# Expose port 80
WORKDIR /usr/share/nginx/html

# Expose port 80
COPY ./dist/ .

# Expose port 80
EXPOSE 80