apiVersion: v1
kind: Service
metadata:
  name: vue3-events-app-frontend-mock-cip
spec:
  type: ClusterIP
  selector:
    app: vue3-events-app-frontend-mock
  ports:
    - protocol: TCP
      port: 80
      # para onde sera redirecionado o trafego
      targetPort: 80
